### ISSUE TITLE
canvas画布大小的问题

### ISSUE THREAD

**Issue by 915644859** [wseven7677/live2d4vue#6]
组件只有 :width 和 :height,可以调整模型整体的比例和大小,但是模型会顶到边框,可以初始化模型的时候,设置模型顶部到canvas顶部的高度吗?

**Comment by wseven7677** [comment]
#2 应该跟这里提到的其中一个问题是一样的，感谢提醒 我好久没有更新这个插件了..

**Comment by wseven7677** [comment]
这里跟 #2 合并下，此处就关闭了。之后也许会出一个统一的解决方案。
