### ISSUE TITLE
想请教一下有没有什么办法直接使用l2d的sdk提供的方法在vue组件中使用l2d模型

### ISSUE THREAD

**Issue by vcJiang** [wseven7677/live2d4vue#9]
最近在做一个小设计，想请教一下有没有什么办法直接使用l2d的sdk提供的方法在vue组件中使用l2d模型。
我这里用的是SDK2的方法，要引入live2d.min.js，pixi.js，pixi-live2d.js，但是报pixi-live2d里面方法没有定义的错，我是参照官方的例子在vue组件里面引入的。现在解决不了这个问题，于是想请教一下你有没有解决办法，或者解决思路，有些急

**Comment by wseven7677** [comment]
我没有用过不太了解哦
